//tealium universal tag - utag.25 ut4.0.202009011416, Copyright 2020 Tealium.com Inc. All Rights Reserved.
window.xtnv=document;window.xtnopage="1";window.xtsd=(window.location.protocol==="https:"?"https://logs1":"http://logc")+"237";window.xtsite="475018";window.xtn2="";window.xtpage="";window.xtdi="";window.xt_multc="";window.xt_an="";window.xt_ac="";window.xttp="";window.xt_ordermc="";window.xt_orderid="";try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
if(utag.ut.typeOf===undefined){u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};}else{u.typeOf=utag.ut.typeOf;}
u.ev={"view":1,"link":1,"hit":1};u.initialized=false;u.scriptrequested=false;u.queue=[];u.map={"xiti_logs":"xtsd","xiti_site_id":"xtsite","xiti_page_name":"xtpage","region_level1_id":"x1","region_level2_id":"x2","region_level3_id":"x3","price_min":"x4","price_max":"x5","category_level1_id":"x6","search_terms":"x8","ad_type_id":"x9","client_type":"x11","features":"x12","neighborhood":"x14","error_msg":"x16","product_name":"f1","group_packs":"x17","user_id":"xt_an","user_role_id":"xt_ac","selected_group_pack":"f1","status":"x18"};u.extend=[function(a,b){try{if(b['environment']!='Prod'){b['xiti_logs']='209'}}catch(e){utag.DB(e);}},function(a,b){try{if(b['environment'].toString().indexOf('Prod')>-1){b['xiti_logs']='237'}}catch(e){utag.DB(e);}},function(a,b){try{if(b['environment'].toString().indexOf('Prod')<0){b['xiti_site_id']='562970'}}catch(e){utag.DB(e);}},function(a,b){try{if(b['environment'].toString().indexOf('Prod')>-1){b['xiti_site_id']='475018'}}catch(e){utag.DB(e);}},function(a,b){try{if(1){b['xiti_page_name']=b['event_name']}}catch(e){utag.DB(e);}},function(a,b,c,d,e,f,g){if(1){d=b['xiti_page_name'];if(typeof d=='undefined')return;c=[{'AdView':'DetallesNew'},{'List':'ResultadosNew'},{'AdViewOfert':'DetallesNewOfert'},{'AdViewGSI':'DetallesNewGSI'}];var m=false;for(e=0;e<c.length;e++){for(f in utag.loader.GV(c[e])){if(d==f){b['xiti_page_name']=c[e][f];m=true};};if(m)break};}},function(a,b){if(b.EventHandler=='EmailContactTracking'){return false;}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,g;u.data={"qsp_delim":"&","kvp_delim":"=","base_url":"//www.fincaraiz.com.co/App_Theme/scripts/xtcore.js","xtn2":"","xtpage":"","xtdi":"","xt_multc":"","xt_an":"","xt_ac":"","xttp":"","xt_ordermc":"","xt_orderid":"","chap1":"","chap2":"","chap3":"","chap4":"","product_id":[],"product_name":[],"product_sku":[],"product_brand":[],"product_category":[],"product_subcategory":[],"product_quantity":[],"product_unit_price":[],"product_discount":[]};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};c=[];for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
u.data.order_id=u.data.order_id||b._corder||"";if(u.data.order_id!==""){u.data.order_total=u.data.order_total||b._ctotal||"";u.data.order_subtotal=u.data.order_subtotal||b._csubtotal||"";u.data.order_shipping=u.data.order_shipping||b._cship||"";u.data.order_tax=u.data.order_tax||b._ctax||"";u.data.order_store=u.data.order_store||b._cstore||"";u.data.order_currency=u.data.order_currency||b._ccurrency||"";u.data.order_coupon_code=u.data.order_coupon_code||b._cpromo||"";u.data.order_type=u.data.order_type||b._ctype||"";u.data.customer_id=u.data.customer_id||b._ccustid||"";u.data.customer_city=u.data.customer_city||b._ccity||"";u.data.customer_state=u.data.customer_state||b._cstate||"";u.data.customer_zip=u.data.customer_zip||b._czip||"";u.data.customer_country=u.data.customer_country||b._ccountry||"";if(u.data.product_id.length===0&&b._cprod!==undefined){u.data.product_id=b._cprod.slice(0);}
if(u.data.product_name.length===0&&b._cprodname!==undefined){u.data.product_name=b._cprodname.slice(0);}
if(u.data.product_sku.length===0&&b._csku!==undefined){u.data.product_sku=b._csku.slice(0);}
if(u.data.product_brand.length===0&&b._cbrand!==undefined){u.data.product_brand=b._cbrand.slice(0);}
if(u.data.product_category.length===0&&b._ccat!==undefined){u.data.product_category=b._ccat.slice(0);}
if(u.data.product_subcategory.length===0&&b._ccat2!==undefined){u.data.product_subcategory=b._ccat2.slice(0);}
if(u.data.product_quantity.length===0&&b._cquan!==undefined){u.data.product_quantity=b._cquan.slice(0);}
if(u.data.product_unit_price.length===0&&b._cprice!==undefined){u.data.product_unit_price=b._cprice.slice(0);}
if(u.data.product_discount.length===0&&b._cpdisc!==undefined){u.data.product_discount=b._cpdisc.slice(0);}}
if(u.data.chap1!==""||u.data.xiti_page_chapter_level1){g=[];if(u.data.chap1)g.push(u.data.chap1);if(u.data.chap2)g.push(u.data.chap2);if(u.data.chap3)g.push(u.data.chap3);if(u.data.chap4)g.push(u.data.chap4);u.data.xtpage=g.join("::");}
u.data.xtn2?u.data.xtn2:"";c.push(u.data.xtpage.replace(/\s/g,"_"));for(var key in u.data){if(!(/xtsite|xtpage|xtsd|base_url|kvp_delim|qsp_delim|chap1|chap2|chap3|chap4/.test(key))&&u.typeOf(u.data[key])!=="array"&&u.data[key]){c.push(key.replace("xt_","")+(u.data.kvp_delim+escape(u.data[key].replace(/\s/g,"_"))));}}
if(u.data.xt_an!==undefined){if(u.data.xt_an!=='')
window.xt_an=u.data.xt_an;}
if(u.data.xt_ac!==undefined){if(u.data.xt_ac!=='')
window.xt_ac=u.data.xt_ac;}
if(u.data.xtsite!==undefined){if(u.data.xtsite!=='')
window.xtsite=u.data.xtsite;}
if(u.data.xtsd!==undefined){if(u.data.xtsd!=='')
window.xtsd=(window.location.protocol==="https:"?"https://logs1":"http://logc")+u.data.xtsd;}
if(u.data.xtn2!==undefined){if(u.data.xtn2!=='')
window.xtn2=u.data.xtn2;}
if(u.data.xtpage!==undefined){if(u.data.xtpage!=='')
window.xtpage=u.data.xtpage;}
u.loader_cb=function(a,b,c){u.initialized=true;u.data.f1=utag_data.product_name!==undefined&&utag_data.product_name!=""?utag_data.product_name:utag_data.selected_group_pack;if(a==="view"){window.xt_med("F",u.data.xtn2,c.join(u.data.qsp_delim));}else if(a==="link"){window.xt_med("C",u.data.xtn2,c.join(u.data.qsp_delim),"A");}else if(a==="hit"){var img=new Image();var rnd=(new String(Math.random())).substring(2,8)+(((new Date()).getTime())&262143);var prT='';prT+=u.data.xt_an!==undefined?"&an="+u.data.xt_an:'';prT+=u.data.xt_ac!==undefined?"&ac="+u.data.xt_ac:'';prT+=u.data.x1!==undefined?"&x1="+u.data.x1:'';prT+=u.data.x2!==undefined?"&x2="+u.data.x2:'';prT+=u.data.x3!==undefined?"&x3="+u.data.x3:'';prT+=u.data.x4!==undefined?"&x4="+u.data.x4:'';prT+=u.data.x5!==undefined?"&x5="+u.data.x5:'';prT+=u.data.x6!==undefined?"&x6="+u.data.x6:'';prT+=u.data.x8!==undefined?"&x8="+u.data.x8:'';prT+=u.data.x9!==undefined?"&x9="+u.data.x9:'';prT+=u.data.x11!==undefined?"&x11="+u.data.x11:'';prT+=u.data.x12!==undefined?"&x12="+u.data.x12:'';prT+=u.data.x14!==undefined?"&x14="+u.data.x14:'';prT+=u.data.x16!==undefined?"&x16="+u.data.x16:'';prT+=u.data.x17!==undefined?"&x17="+u.data.x17:'';prT+=u.data.x18!==undefined?"&x18="+u.data.x18:'';prT+=u.data.f1!==undefined?"&f1="+u.data.f1:'';img.src=window.xtsd+'.xiti.com/hit.xiti?s='+window.xtsite+prT+"&p="+window.xtpage+"&rndm="+rnd;}};u.callBack=function(){var data={};while(data=u.queue.shift()){u.data=data.data;b=data.b;c=data.c;u.loader_cb(data.a,data.b,data.c);}};if(u.initialized){u.loader_cb(a,b,c);}else{u.queue.push({"data":u.data,"b":b,"a":a,"c":c});if(!u.scriptrequested){u.scriptrequested=true;u.loader({"type":"script","src":u.data.base_url,"cb":u.callBack,"loc":"script","id":'utag_25'});}}
}};utag.o[loader].loader.LOAD(id);}("25","schibsted.fincaraiz"));}catch(error){utag.DB(error);}
